### ISSUE TITLE
"Load failed" error

### ISSUE THREAD

**Issue by smd75jr** [terrybroad/Learned-Sim-Autoencoder-For-Video-Frames#4]
While trying to train or run, it throws a warning saying `[!] Load Failed`. Looking at the code, this seems to be related to the checkpoint directory, however, I have never actually seen the directory used (it has never had any files in it).

**Comment by terrybroad** [comment]
You can only run the model if you have trained and saved one. In this version of the code, the model is only saved once 1000 mini-batches have been processed, this can be changed in line 245 of model.py 

`if np.mod(counter, 500) == 2 and counter > 450:
                    self.save(config.checkpoint_dir, counter)
`
I have now edited the readme to clarify this issue.

**Comment by jakeelwes** [comment]
Heya Terence - I know this was ages ago, but seem to also be getting `[!] Load failed.` when trying to train (not run) - Sweet project by the way, wanted to have a go at reconstructing some random clips & sound with rnn's (dont know if you have any suggestions for more recent projects for reconstructing video), managed to get tf0.7.0 running on nvidia-docker. Thanks :)
